---
- hosts: all
  become: true
  roles:
    - common

- hosts: control_plane
  become: true
  roles:
    - airflow

- hosts: data_plane
  become: true
  roles:
    - spark

- hosts: storage
  become: true
  roles:
    - minio
